import { VeltComments, VeltCommentsSidebar, VeltCommentTool, VeltCursor } from '@veltdev/react';
import Head from 'next/head';
import React, { useState } from 'react';
import styles from '../../styles/Home.module.css';
import Tabs from '../components/Tabs/Tabs';
import Toolbar from '../components/Toolbar/Toolbar';

export default function Home() {

  const [selectedMenu, setSelectedMenu] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Velt Nextjs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VeltCursor />
      <VeltComments />
      <VeltCommentsSidebar />
      <VeltCommentTool />
      <Toolbar onMenuSelect={(menu) => setSelectedMenu(menu)} />
      <Tabs selectedMenu={selectedMenu} />
    </div>
  )
}
