import { SnippylyComments, SnippylyCommentsSidebar, SnippylyCommentTool, SnippylyCursor } from '@snippyly/react';
import Head from 'next/head';
import React, { useState } from 'react';
import styles from '../../styles/Home.module.css';
import Tabs from '../components/Tabs/Tabs';
import Toolbar from '../components/Toolbar/Toolbar';

export default function Home() {

  const [selectedMenu, setSelectedMenu] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Snippyly Nextjs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SnippylyCursor />
      <SnippylyComments />
      <SnippylyCommentsSidebar />
      <SnippylyCommentTool />
      <Toolbar onMenuSelect={(menu) => setSelectedMenu(menu)} />
      <Tabs selectedMenu={selectedMenu} />
    </div>
  )
}
