import Head from 'next/head';
import React, { useState } from 'react';
import styles from '../../styles/Home.module.css';
import Tabs from '../components/Tabs/Tabs';
import Toolbar from '../components/Toolbar/Toolbar';

export default function Home() {

  const [selectedMenu, setSelectedMenu] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Snippyly Nextjs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <snippyly-cursor></snippyly-cursor>
      <snippyly-comments></snippyly-comments>
      <snippyly-comment-tool>
        <div className='add-comment-btn'>
          <img src='https://cdn-icons-png.flaticon.com/512/727/727570.png' alt='Add comment' />
        </div>
      </snippyly-comment-tool>
      <Toolbar onMenuSelect={(menu) => setSelectedMenu(menu)} />
      <Tabs selectedMenu={selectedMenu} />
    </div>
  )
}
